spring:
  application:
    name: individuals-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
app:
  keycloak:
    admin:
      clientId: servlet-app
      clientSecret: 9kKNQwDNgy8nDamUCdPKbgr4FTZGNgPM
    realm: individuals-api
    serverUrl: http://localhost:8080
server:
  port: 8081
