spring:
  application:
    name: Individuals-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: YEO1Os7WQ9UGIIHQJPwSDakADpiOzjNY
    realm: master
    serverUrl: http://localhost:8080
server:
  port: 8081
logging:
  level:
    org.springframework: DEBUG
    org.keycloak: DEBUG