spring:
  application:
    name: Individuals-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
          introspect-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}/protocol/openid-connect/token/introspect
app:
  keycloak:
    admin:
      client-id: admin-cli
      client-secret: K6WL44pGrZY06owquPG1TdDam51GPi61
      username: admin
      password: admin
    realm: master
    user-auth-tokens:
      client-id: user-auth-tokens
      client-secret: OBUCR6mlUeZhoATQEEqON8YjBGUqvGHu
    user-exchange-tokens:
      client-id: user-exchange-tokens
      client-secret: A6RMYlO04h4KihPYgjgWe4fP10GRnQHN
    serverUrl: http://localhost:8080
server:
  port: 8081
logging:
  level:
    org.springframework: DEBUG
    org.keycloak: DEBUG
person:
  api:
    registration-url: http://localhost:8083/api/v1/auth/registration
    remove-url: http://localhost:8083/api/v1/auth/remove