{
  "formatVersion": "1.1",
  "component": {
    "group": "com.umaraliev",
    "module": "common",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.1-SNAPSHOT-plain.jar",
          "url": "common-0.0.1-SNAPSHOT-plain.jar",
          "size": 4075,
          "sha512": "d0370ee7a6b8cd7683277cdb67138a0fb0d640a9a96ab111a525577b99777a3ac6cd217d3a40808d6dc98c043e82ef95963d795bf6acf31c523176d6461eb809",
          "sha256": "353b2d665648c0114619ca81d9195d1703590b22c69e41eb467f13d092ca5e18",
          "sha1": "67aabf4a630dc73324500a31b108ac58e10c0875",
          "md5": "e7394ee3f0d751aaa290d40d43099762"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.1-SNAPSHOT-plain.jar",
          "url": "common-0.0.1-SNAPSHOT-plain.jar",
          "size": 4075,
          "sha512": "d0370ee7a6b8cd7683277cdb67138a0fb0d640a9a96ab111a525577b99777a3ac6cd217d3a40808d6dc98c043e82ef95963d795bf6acf31c523176d6461eb809",
          "sha256": "353b2d665648c0114619ca81d9195d1703590b22c69e41eb467f13d092ca5e18",
          "sha1": "67aabf4a630dc73324500a31b108ac58e10c0875",
          "md5": "e7394ee3f0d751aaa290d40d43099762"
        }
      ]
    }
  ]
}
